version: "3.0"

services:

  api:
    build:
      context: .
    image: config
    env_file: docker-compose.env
    environment:
      SERVICES: .
      PORT: 3000
    links:
      - redis
    depends_on:
      - redis

  redis:
    image: redis:alpine
